apiVersion: v2
name: greencity-backcore
description: GreenCity BackCore chart
type: application
version: $CHART_VERSION # chart version
appVersion: "0.0.1-snapshot" # application version
appversion: $APP_VERSION
