namespace: greencity
replicaCount: 2
labels:
  app: greencity
  tier: backcore
  tags.datadoghq.com/env: "prod"
  tags.datadoghq.com/service: "greencity-backcore"
  tags.datadoghq.com/version: "0.0.1"
selectorLabels:
  app: greencity
  tier: backcore
podLabels:
  app: greencity
  tier: backcore
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 50%
    maxUnavailable: 50%
restartPolicy: Always
# 084912621610.dkr.ecr.us-east-1.amazonaws.com/greencity/backcore:5@sha256:97b247a9370b3b80a2fa2de3348787fd99c8ae919c805ab349c55d19f2326054
image:
  repository: 084912621610.dkr.ecr.us-east-1.amazonaws.com/greencity/backcore
  tag: 0.0.1-snapshot-5c1df86b3f8699a3043777db6e46d7afd576fbf6
  sha256: sha256:ef9a533834556146e2ec3d42027b5d0ead49a596d6c8fd494bd69e537cf738cc
  pullPolicy: IfNotPresent
imagePullSecrets: []
containerName: backcore
resources:
  limits:
    cpu: 2000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 512Mi
securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  seccompProfile:
    type: RuntimeDefault
podSecurityContext:
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  allowPrivilegeEscalation: false
  # appArmorProfile:
  #   type: RuntimeDefault
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop:
      - ALL
volumes:
  - name: backcore-log
    emptyDir:
      sizeLimit: 300Mi
  - name: tmpfs
    emptyDir:
      sizeLimit: 300Mi
  - name: backcore-secret-volume
    secret:
      secretName: greencity-backcore-secret
volumeMounts:
  - name: backcore-log
    mountPath: /app/logs
  - name: tmpfs
    mountPath: /tmp
  - name: backcore-secret-volume
    mountPath: /run/secrets/app
    readOnly: true
# envFrom:
#   - configMapRef:
#       name: greencity-backcore-env
env:
  - name: BACKCORE_URL
    value: http://$(BACKCORE_HOST):$(BACKCORE_PORT)
  - name: BACKUSER_URL
    value: http://$(BACKUSER_HOST):$(BACKUSER_PORT)
  - name: FRONTEND_URL
    value: https://$(FRONTEND_HOST)
  - name: ECONEWS_URL
    value: $(FRONTEND_URL)/welcome
  - name: CHAT_URL
    value: http://$(CHAT_HOST):$(CHAT_PORT)
service:
  type: ClusterIP
  port: 8080
livenessProbe:
  httpGet:
    port: 8080
    path: /actuator/health/liveness
    scheme: HTTP
  initialDelaySeconds: 200
  periodSeconds: 60
  timeoutSeconds: 15
  failureThreshold: 5
readinessProbe:
  httpGet:
    port: 8080
    path: /actuator/health/readiness
    scheme: HTTP
  initialDelaySeconds: 200
  periodSeconds: 60
  timeoutSeconds: 15
  failureThreshold: 5
configMapData:
  PROFILE: docker
  SPRING_CONFIG_IMPORT_SECRETS: optional:configtree:/run/secrets/app/
  DATASOURCE_TYPE: postgresql
  DATASOURCE_DRIVER: org.postgresql.Driver
  # DATASOURCE_HOST: database
  DATASOURCE_PORT: '5432'
  # DATASOURCE_NAME: greencity
  # DATASOURCE_USER: greencity
  LIQUIB_ENABLED: 'true'
  LIQUIB_CHANGELOG: classpath:db/changelog/db.changelog-master.xml
  LIQUIB_SERVICE_EMAIL: service@greencity.ua
  HIBERNATE_DDL_AUTO: validate
  HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
  SHOW_SQL: 'true'
  JDBC_LOB: 'true'
  MAIL_HOST: smtp.gmail.com
  MAIL_PORT: '587'
  SMTP_AUTH: 'true'
  SMTP_TLS_ENABLED: 'true'
  BACKCORE_HOST: backcore
  BACKCORE_PORT: '8080'
  BACKUSER_HOST: backuser
  BACKUSER_PORT: '8060'
  CHAT_HOST: chat
  CHAT_PORT: '8030'
  FRONTEND_HOST: lerkasan.net
  FRONTEND_PORT: '80'
  TOKEN_ACCESS_TIME: '120'
  TOKEN_REFRESH_TIME: '600'
  VERIFY_EMAIL_HOURS: '24'
  MAX_FILE_SIZE: 2MB
  MAX_REQUEST_SIZE: 2MB
  MAX_HTTP_FORM_POST_SIZE: 2MB
  LOG_LEVEL_ROOT: info
  LOG_EXCEPTION_HANDLER: trace
  CLOUD_NAME: greencity-lv448java
  BUCKET_NAME: staging.greencity-c5a3a.appspot.com
  STATIC_URL: https://storage.cloud.google.com/
  DEFAULT_PROFILE_PICTURE: https://storage.cloud.google.com/staging.greencity-c5a3a.appspot.com/3d1a4092-c31e-4a0f-814b-57a0e4de0851
  GOOGLE_APPLICATION_CREDENTIALS: /app/google-creds.json
  EndpointSuffix: core.windows.net
  AZURE_CONTAINER_NAME: allfiles
  TIME_AFTER_LAST_ACTIVITY: '300000'
  DD_SERVICE: greencity-backcore
  DD_ENV: prod
  DD_VERSION: 0.0.1
  DD_AGENT_HOST: datadog-agent
externalSecret:
  region: us-east-1
  refreshInterval: 1h
  serviceAccount: external-secrets-account
externalSecretData:
  - secretKey: DATASOURCE_HOST
    remoteRef:
      key: greencity_database_host
  - secretKey: DATASOURCE_NAME
    remoteRef:
      key: greencity_database_name
  - secretKey: DATASOURCE_USER
    remoteRef:
      key: greencity_database_username
  - secretKey: DATASOURCE_PASSWORD
    remoteRef:
      key: greencity_database_password
  - secretKey: API_KEY
    remoteRef:
      key: greencity_api_key
  - secretKey: API_SECRET
    remoteRef:
      key: greencity_api_secret
  - secretKey: AZURE_CONNECTION_STRING
    remoteRef:
      key: greencity_azure_connection_string
  - secretKey: EMAIL_ADDRESS
    remoteRef:
      key: greencity_email_address
  - secretKey: EMAIL_PASSWORD
    remoteRef:
      key: greencity_email_password
  - secretKey: GOOGLE_API_KEY
    remoteRef:
      key: greencity_google_api_key
  - secretKey: GOOGLE_CLIENT_ID
    remoteRef:
      key: greencity_google_client_id
  - secretKey: GOOGLE_CLIENT_ID_MANAGER
    remoteRef:
      key: greencity_google_client_id_manager
  - secretKey: TOKEN_KEY
    remoteRef:
      key: greencity_token_key
  - secretKey: google-creds.json
    remoteRef:
      key: greencity_google_creds_json
