apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.clusterSecretStoreName }}
    kind: ClusterSecretStore
  target:
    name: greencity-backcore-secret
    creationPolicy: Owner
  data:
  {{- toYaml .Values.externalSecretData | nindent 2 }}